export { default as Arrow } from './Arrow'
export { default as Camera } from './Camera'
export { default as Gallery } from './Gallery'
export { default as Home } from './Home'
export { default as Spotify } from './Spotify'
export { default as Youtube } from './Youtube'